# Generated by Django 2.1.1 on 2018-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='program',
            name='student',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
